export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const LOAD_CART_ITEMS = "LOAD_CART_ITEMS";

export const CLEAR_CART_ON_LOGOUT = "CLEAR_CART_ON_LOGOUT";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export const UPDATE_ORDER_HISTORY = "UPDATE_ORDER_HISTORY";

